apiVersion: config.ocm.software/v1alpha1
kind: PipelineTemplate
metadata:
  name: podify-pipeline-template
steps:
- name: resource
  template:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    metadata:
      name: {{ .Parameters.Name }}
      namespace: {{ .Component.Namespace }}
    spec:
      interval: 1m0s
      sourceRef:
        kind: ComponentVersion
        name: podify
        namespace: {{ .Component.Namespace }}
        resourceRef:
          name: {{ .Resource }}
          version: latest
          {{ with .Component.Reference  }}
          referencePath:
            name: {{ . }}
          {{ end }}
- name: localize
  template:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Localization
    metadata:
      name: {{ .Parameters.Name }}
      namespace: {{ .Component.Namespace }}
    spec:
      interval: 1m0s
      sourceRef:
        kind: Resource
        name: {{ .Parameters.Name }}
        namespace: {{ .Component.Namespace }}
      configRef:
        kind: ComponentVersion
        name: podify
        namespace: {{ .Component.Namespace }}
        resourceRef:
          name: config
          {{ with .Component.Reference  }}
          referencePath:
            - name: {{ . }}
          {{ end }}
- name: config
  template:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Configuration
    metadata:
      name: {{ .Parameters.Name }}
      namespace: {{ .Component.Namespace }}
    spec:
      interval: 1m0s
      sourceRef:
        kind: Localization
        name: {{ .Parameters.Name }}
        namespace: {{ .Component.Namespace }}
      configRef:
        kind: ComponentVersion
        name: podify
        namespace: {{ .Component.Namespace }}
        resourceRef:
          name: config
          {{ with .Component.Reference  }}
          referencePath:
            - name: {{ . }}
          {{ end }}
      values: {{ .Values | toYaml | nindent 8 }}
- name: flux-kustomization
  template:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: FluxDeployer
    metadata:
      name: podinfo
      namespace: ocm-system
    spec:
      sourceRef:
        kind: Configuration
        name: {{ .Parameters.Name }}
        namespace: {{ .Component.Namespace }}
      kustomizationTemplate:
        interval: 1m0s
        path: ./
        prune: true
        targetNamespace: default
