# permissions for end users to edit componentsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentsync-editor-role
rules:
- apiGroups:
  - transfer.phoban.io
  resources:
  - componentsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transfer.phoban.io
  resources:
  - componentsyncs/status
  verbs:
  - get
