# permissions for end users to edit realizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: realization-editor-role
rules:
- apiGroups:
  - transfer.phoban.io
  resources:
  - realizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transfer.phoban.io
  resources:
  - realizations/status
  verbs:
  - get
