---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transfer.phoban.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transfer.phoban.io
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - transfer.phoban.io
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - transfer.phoban.io
  resources:
  - realizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transfer.phoban.io
  resources:
  - realizations/finalizers
  verbs:
  - update
- apiGroups:
  - transfer.phoban.io
  resources:
  - realizations/status
  verbs:
  - get
  - patch
  - update
