# permissions for end users to view transformations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transformation-viewer-role
rules:
- apiGroups:
  - transfer.phoban.io
  resources:
  - transformations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transfer.phoban.io
  resources:
  - transformations/status
  verbs:
  - get
