# permissions for end users to edit transformations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transformation-editor-role
rules:
- apiGroups:
  - transfer.phoban.io
  resources:
  - transformations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transfer.phoban.io
  resources:
  - transformations/status
  verbs:
  - get
