apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: queue-master-config
localization:
- resource:
    name: app-image
  file: queue-master-dep.yaml
  image: spec.template.spec.containers[0].image
- resource:
    name: redis-management-image
  file: rabbitmq-dep.yaml
  image: spec.template.spec.containers[0].image
- resource:
    name: redis-exporter-image
  file: rabbitmq-dep.yaml
  image: spec.template.spec.containers[1].image
- resource:
    name: session-image
  file: session-db-dep.yaml
  image: spec.template.spec.containers[0].image