apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: user-config
localization:
- resource:
    name: app-image
  file: user-dep.yaml
  image: spec.template.spec.containers[0].image
- resource:
    name: db-image
  file: user-db-dep.yaml
  image: spec.template.spec.containers[0].image